### ISSUE TITLE
panic: proto: file "openapiv2/OpenAPIv2.proto" has a name conflict over openapi.v2.Xml

### ISSUE THREAD

**Issue by Bryce-Soghigian** [google/gnostic#380]
Using gnostic@v0.6.9, I am getting this error. Its a dependency of another project never worked with gnostic before.

panic: proto: file "openapiv2/OpenAPIv2.proto" has a name conflict over openapi.v2.Xml
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x22fda20?, 0xc000190a10?}, {0x22fda20?, 0xc000190a10})
        /Users/bsoghigian/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoregistry/registry.go:56 +0x1ee
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile.func1({0x2314f18, 0xc0002d79f0})
        /Users/bsoghigian/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoregistry/registry.go:154 +0x279
google.golang.org/protobuf/reflect/protoregistry.rangeTopLevelDescriptors({0x23192f0, 0xc00058e1c0}, 0xc00041f158)
        /Users/bsoghigian/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoregistry/registry.go:417 +0x171
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0001a4048, {0x23192f0?, 0xc00058e1c0?})
        /Users/bsoghigian/go/pkg/mod/google.golang.org/protobuf@v1.28.1/reflect/protoregistry/registry.go:149 +0x739
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x1e59f74, 0x23}, {0x2cc4400, 0x3afc, 0x3afc}, 0x0, 0x3c, 0x0, 0x0, {0x2301c18, ...}, ...})
        /Users/bsoghigian/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/filedesc/build.go:112 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x1e59f74, 0x23}, {0x2cc4400, 0x3afc, 0x3afc}, 0x0, 0x3c, 0x0, 0x0, {0x0, ...}, ...}, ...})
        /Users/bsoghigian/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/filetype/build.go:138 +0x1b8
github.com/google/gnostic/openapiv2.file_openapiv2_OpenAPIv2_proto_init()
        /Users/bsoghigian/go/pkg/mod/github.com/google/gnostic@v0.6.9/openapiv2/OpenAPIv2.pb.go:7337 +0x578
github.com/google/gnostic/openapiv2.init.0()
        /Users/bsoghigian/go/pkg/mod/github.com/google/gnostic@v0.6.9/openapiv2/OpenAPIv2.pb.go:6563 +0x17

**Comment by timburks** [comment]
Thanks, I think we should move forward and restructure the protos to match [this draft](https://buf.build/gnostic/gnostic). I'll start that.

**Comment by yipeng1030** [comment]
Hello everyone, I'm wondering if this issue has been resolved in any of the released versions?
